apiVersion: v1
kind: Pod
metadata:
  name: unsafe-sysctls-pod
  namespace: crowdstrike-detections
spec:
  containers:
    - name: unsafe-sysctls-container
      image: nginx
      securityContext:
        sysctls:
          - name: kernel.msgmax
            value: "65536"
