apiVersion: v1
kind: Service
metadata:
  name: node-port-service
  namespace: crowdstrike-detections
spec:
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
