apiVersion: v1
kind: Pod
metadata:
  name: service-account-token-automount-pod
  namespace: crowdstrike-detections
spec:
  automountServiceAccountToken: true
  containers:
    - name: service-account-token-automount-container
      image: nginx
