apiVersion: apps/v1
kind: Deployment
metadata:
  name: detections-container
  namespace: crowdstrike-detections
spec:
  selector:
   matchLabels:
      run: detections-container
  replicas: 1
  template:
    metadata:
      labels:
        run: detections-container
    spec:
      containers:
          - name: detections-container
            image: quay.io/crowdstrike/detection-container
            imagePullPolicy: Always
            command:
              - "/entrypoint.sh"
            ports:
             - containerPort: 8080
               name: web
