apiVersion: v1
kind: Pod
metadata:
  name: sysadmin-capability-pod
  namespace: crowdstrike-detections
spec:
  containers:
    - name: sysadmin-capability-container
      image: nginx
      securityContext:
        capabilities:
          add:
            - SYS_ADMIN
