apiVersion: v1
kind: Pod
metadata:
  name: network-capabilities-pod
  namespace: crowdstrike-detections
spec:
  containers:
    - name: network-capabilities-container
      image: nginx
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
