apiVersion: v1
kind: Pod
metadata:
  name: host-pid-namespace-pod
  namespace: crowdstrike-detections
spec:
  containers:
    - name: host-pid-namespace-container
      image: nginx
      securityContext:
        runAsUser: 0
  hostPID: true  # This shares PID namespace with the host
