apiVersion: v1
kind: Pod
metadata:
  name: host-port-pod
  namespace: crowdstrike-detections
spec:
  containers:
    - name: host-port-container
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
