apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: crowdstrike-detections
spec:
  containers:
    - name: privileged-container
      image: nginx
      securityContext:
        privileged: true
