apiVersion: v1
kind: Pod
metadata:
  name: unconfined-seccomp-pod
  namespace: crowdstrike-detections
spec:
  containers:
    - name: unconfined-seccomp-container
      image: nginx
      securityContext:
        seccompProfile:
          type: Unconfined
